#Database
POSTGRES_SQL_USERNAME: <DB USERNAME>
POSTGRES_SQL_PASSWORD: <DB PASSWORD>
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: umdb

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <YOUR EMAIL ADDRESS>
EMAIL_PASSWORD: <YOUR PASSWORD>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}